m: add colored log, remove green() yellow()

diff --git a/dot_config/zsh/dot_zshrc b/dot_config/zsh/dot_zshrc
--- a/dot_config/zsh/dot_zshrc
+++ b/dot_config/zsh/dot_zshrc
@@ -28,13 +28,10 @@ function h() {
 # }}}
 
 ## util {{{
-green() {
-    print "\033[1;32m$*\033[0m"
-}
-
-yellow() {
-    print "\033[1;33m$*\033[0m"
-}
+info()    { printf '\e[1;34m[INFO]\e[0m  %s\n' "$*"; }
+success() { printf '\e[1;32m[OK]\e[0m    %s\n' "$*"; }
+warn()    { printf '\e[1;33m[WARN]\e[0m  %s\n' "$*"; }
+die()     { printf '\e[1;31m[ERR]\e[0m   %s\n' "$*" >&2; exit 1; }
 
 co() { # edit zshrc
     nvim $ZDOTDIR/.zshrc
@@ -42,7 +39,7 @@ co() { # edit zshrc
 
 so() { # reload zshrc
     source $ZDOTDIR/.zshrc
-    green "reload .zshrc"
+    success "reload .zshrc"
 }
 
 function sora() { # Time and weather
@@ -64,7 +61,7 @@ dotstatus() {
 # chezmoi add -> git add -> git commit
 dotpush() {
     local fn=$(dotstatus)
-    [[ "$fn" == "" ]] && green "not modified" && return 0
+    [[ "$fn" == "" ]] && success "not modified" && return 0
 
     chezmoi diff $fn --reverse  | tail -n +6 | batcat -l diff
     echo "Add and commit? [Enter to continue / q to quit]: "
@@ -168,7 +165,7 @@ zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' '+m:{[:upper:]}=
 if [[ -a $ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
     source $ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh
 else
-    yellow "    PLUGIN NOT FOUND: zsh-autosuggestions"
+    warn "    PLUGIN NOT FOUND: zsh-autosuggestions"
     echo   "    follow this command:"
     echo   "git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_PLUGINS/zsh-autosuggestions"
     echo   ""
@@ -225,7 +222,7 @@ setopt hist_ignore_space
 if [[ -a $ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
     source $ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
 else
-    yellow "   PLUGIN NOT FOUND: zsh-syntax-highlighting"
+    warn "   PLUGIN NOT FOUND: zsh-syntax-highlighting"
     echo   "   follow this command:"
     echo   "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_PLUGINS/plugins/zsh-syntax-highlighting/"
     echo   ""
@@ -236,7 +233,7 @@ fi
 if [[ -a /usr/local/bin/starship ]]; then
     eval "$(starship init zsh)"
 else
-    yellow "   PLUGIN NOT FOUND: Starship"
+    warn "   PLUGIN NOT FOUND: Starship"
     echo   "   follow this command (maybe):"
     echo   "curl -sS https://starship.rs/install.sh | sh"
     echo   ""
@@ -248,7 +245,7 @@ fi
 gitautoadd() {
     local fn
     igt status --short | head -n 1 | sed 's/.../~\//' | read fn
-    [[ "$fn" == "" ]] && green "not modified" && return 0
+    [[ "$fn" == "" ]] && success "not modified" && return 0
 
     git add fn
     git commit
